<a href="https://colab.research.google.com/github/AishwaryaN2203/Deep_Learning/blob/main/Autograd_with_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Autograd with tensors

- Autograd is used for automatically calculating the gradients of tensors
- Keeps track of operations performed on tensors and then going backwards through there operations, calculating gradients along the way

In [1]:
import torch

In [2]:
w = torch.randn(4,3, requires_grad=True)
w

tensor([[-0.4606, -0.8573, -0.1165],
        [ 0.9729,  0.0966, -0.3621],
        [ 0.4838, -0.1181,  2.1014],
        [-0.0511, -2.4486, -2.2380]], requires_grad=True)

In [3]:
t = torch.randn(4,3, requires_grad=False)
t

tensor([[-0.3079,  0.4855, -0.8610],
        [ 1.0824, -0.8682,  0.3224],
        [-0.9010, -0.9534,  0.9760],
        [ 0.4891,  0.0157,  0.3562]])

In [4]:
# y holds the exponent of the tensor w (y = e^w )
y = torch.exp(w)
y

tensor([[0.6309, 0.4243, 0.8900],
        [2.6457, 1.1014, 0.6962],
        [1.6223, 0.8886, 8.1779],
        [0.9502, 0.0864, 0.1067]], grad_fn=<ExpBackward0>)

In [5]:
# Autograd modeule keeps track of these operations and knows how to calculate the gradient for each one
print(y.grad_fn)

In [6]:
outp = y.mean()
outp

tensor(1.5184, grad_fn=<MeanBackward0>)

In [7]:
print(w.grad)

None


In [8]:
outp.backward()

In [9]:
print(w.grad)

tensor([[0.0526, 0.0354, 0.0742],
        [0.2205, 0.0918, 0.0580],
        [0.1352, 0.0741, 0.6815],
        [0.0792, 0.0072, 0.0089]])


In [10]:
# To stop the tensor from tracking history, you can call the detach method to detach it from computation history
print(w.detach())

tensor([[-0.4606, -0.8573, -0.1165],
        [ 0.9729,  0.0966, -0.3621],
        [ 0.4838, -0.1181,  2.1014],
        [-0.0511, -2.4486, -2.2380]])


In [11]:
# To prevent tracking history
# Eg: Model might have trainable parameters
print(outp.requires_grad)

True


In [14]:
with torch.no_grad():
  outp = (w+y).mean()

print(outp.requires_grad)

False


In [15]:
print(outp.requires_grad)

False
