<a href="https://colab.research.google.com/github/AishwaryaN2203/Deep_Learning/blob/main/Tensors_Operations_using_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors

In [ ]:
import torch

## zeros()

In [ ]:
w = torch.zeros(4,3)

.zeros(param1, param2)

param1 = no of rows
param2 = no of columns

In [ ]:
w

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## size() and shape

In [ ]:
w.size()

torch.Size([4, 3])

In [ ]:
w.shape

torch.Size([4, 3])

## randn() and randn_like()

In [ ]:
w = torch.randn(4,3)
w

tensor([[ 0.3864, -1.9321,  1.0684],
        [ 0.7906,  0.2255,  0.1451],
        [ 1.5294,  0.0881,  1.4176],
        [-2.0385,  0.3484,  0.6397]])

In [ ]:
# randn_like is used to get another random function like a already exisitng tensor
t = torch.randn_like(w)
t

tensor([[ 0.7213,  0.2350, -0.1478],
        [-2.8230, -1.9241, -0.1945],
        [ 0.8145, -1.0050, -0.0583],
        [ 1.1240,  0.3117,  0.2611]])

## fill_()

In [ ]:
w.fill_(1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

All pytorch function which is followed by an underscore mutates the function in place

## view()

In [ ]:
w

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
t = w.view(3,4)
t

# to view/ reshape the tensor to a different dimension

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
w.view(3, -1)

# To avoid calculation we can use -1 after specifying either row or column

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## numpy()

In [ ]:
# Torch tensor to numpy array

type(w.numpy())

numpy.ndarray